*** Starting uWSGI 2.0.15 (64bit) on [Fri Jun  9 15:12:13 2017] ***
compiled with version: 5.4.0 20160609 on 28 May 2017 16:03:49
os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017
nodename: ccy-virtual-machine
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ccy/Desktop/pytest/ttsx/dailyfresh/ttshx
writing pidfile to uwsgi.pid
detected binary path: /home/ccy/.virtualenvs/ttsx/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ccy/Desktop/pytest/ttsx/dailyfresh/ttshx
your processes number limit is 5886
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8080 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x19a54e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 415280 bytes (405 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19a54e0 pid: 13685 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13685)
spawned uWSGI worker 1 (pid: 13688, cores: 2)
spawned uWSGI worker 2 (pid: 13689, cores: 2)
spawned uWSGI worker 3 (pid: 13690, cores: 2)
spawned uWSGI worker 4 (pid: 13691, cores: 2)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 736 bytes} [Fri Jun  9 15:13:43 2017] GET / => generated 0 bytes in 756 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 710 bytes} [Fri Jun  9 15:13:44 2017] GET /favicon.ico => generated 0 bytes in 103 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 3/3] 127.0.0.1 () {40 vars in 746 bytes} [Fri Jun  9 15:16:11 2017] GET /user/ => generated 0 bytes in 27 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 4/4] 127.0.0.1 () {40 vars in 715 bytes} [Fri Jun  9 15:16:12 2017] GET /favicon.ico => generated 0 bytes in 14 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 5/5] 127.0.0.1 () {40 vars in 715 bytes} [Fri Jun  9 15:21:04 2017] GET /favicon.ico => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 6/6] 127.0.0.1 () {40 vars in 736 bytes} [Fri Jun  9 15:21:09 2017] GET / => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 7/7] 127.0.0.1 () {40 vars in 710 bytes} [Fri Jun  9 15:21:09 2017] GET /favicon.ico => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 8/8] 127.0.0.1 () {42 vars in 767 bytes} [Fri Jun  9 15:21:15 2017] GET / => generated 0 bytes in 9 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13689|app: 0|req: 1/9] 127.0.0.1 () {44 vars in 763 bytes} [Fri Jun  9 15:21:15 2017] GET /favicon.ico => generated 0 bytes in 102 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13689|app: 0|req: 2/10] 127.0.0.1 () {44 vars in 789 bytes} [Fri Jun  9 15:21:17 2017] GET / => generated 0 bytes in 18 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 9/11] 127.0.0.1 () {44 vars in 763 bytes} [Fri Jun  9 15:21:17 2017] GET /favicon.ico => generated 0 bytes in 9 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 10/12] 127.0.0.1 () {42 vars in 767 bytes} [Fri Jun  9 15:21:30 2017] GET / => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 11/13] 127.0.0.1 () {40 vars in 710 bytes} [Fri Jun  9 15:21:30 2017] GET /favicon.ico => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 12/14] 127.0.0.1 () {42 vars in 767 bytes} [Fri Jun  9 15:23:17 2017] GET / => generated 0 bytes in 16 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./ttshx/urls.py", line 22, in <module>
    url(r'^',include('goods.urls')),
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./goods/urls.py", line 2, in <module>
    from . import views
  File "./goods/views.py", line 77, in <module>
    from haystack.views import SearchView
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 16, in <module>
    class SearchView(object):
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/views.py", line 20, in SearchView
    results = EmptySearchQuerySet()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 29, in __init__
    self._determine_backend()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/query.py", line 62, in _determine_backend
    self.query = connections[backend_alias].get_query()
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 108, in __getitem__
    self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 59, in load_backend
    return import_class(full_backend_path)
  File "/home/ccy/.virtualenvs/ttsx/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 26, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named whoosh_cn_backend
[pid: 13691|app: 0|req: 13/15] 127.0.0.1 () {40 vars in 710 bytes} [Fri Jun  9 15:23:17 2017] GET /favicon.ico => generated 0 bytes in 9 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 13691|app: 0|req: 14/16] 127.0.0.1 () {44 vars in 789 bytes} [Fri Jun  9 15:38:16 2017] GET / => generated 13413 bytes in 3181 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 1)
[pid: 13691|app: 0|req: 15/17] 127.0.0.1 () {44 vars in 759 bytes} [Fri Jun  9 15:38:20 2017] GET /js/slideshow.js => generated 89 bytes in 139 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 16/18] 127.0.0.1 () {44 vars in 774 bytes} [Fri Jun  9 15:38:22 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 13688|app: 0|req: 1/19] 127.0.0.1 () {40 vars in 738 bytes} [Fri Jun  9 15:38:23 2017] GET /favicon.ico => generated 85 bytes in 1100 msecs (HTTP/1.1 404) 3 headers in 125 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 17/20] 127.0.0.1 () {42 vars in 817 bytes} [Fri Jun  9 15:39:06 2017] GET /user/logout/ => generated 0 bytes in 454 msecs (HTTP/1.1 302) 4 headers in 203 bytes (1 switches on core 1)
[pid: 13688|app: 0|req: 2/21] 127.0.0.1 () {42 vars in 749 bytes} [Fri Jun  9 15:39:06 2017] GET / => generated 13444 bytes in 293 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 1)
[pid: 13691|app: 0|req: 18/22] 127.0.0.1 () {40 vars in 662 bytes} [Fri Jun  9 15:39:07 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 13690|app: 0|req: 1/23] 127.0.0.1 () {40 vars in 677 bytes} [Fri Jun  9 15:39:07 2017] GET /js/slideshow.js => generated 89 bytes in 280 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 19/24] 127.0.0.1 () {42 vars in 775 bytes} [Fri Jun  9 15:39:08 2017] GET /user/login/ => generated 3056 bytes in 19 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 1)
[pid: 13690|app: 0|req: 2/25] 127.0.0.1 () {50 vars in 971 bytes} [Fri Jun  9 15:39:23 2017] POST /user/login_handle/ => generated 3056 bytes in 189 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 1)
读取cookie
{'csrftoken': 'szc7NiGl0E5p2fep5V6abnknkyKADFZM', 'red_url': '/js/slideshow.js'}
[pid: 13691|app: 0|req: 20/26] 127.0.0.1 () {50 vars in 978 bytes} [Fri Jun  9 15:39:34 2017] POST /user/login_handle/ => generated 0 bytes in 219 msecs (HTTP/1.1 302) 7 headers in 399 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 21/27] 127.0.0.1 () {44 vars in 864 bytes} [Fri Jun  9 15:39:34 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 13688|app: 0|req: 3/28] 127.0.0.1 () {40 vars in 780 bytes} [Fri Jun  9 15:39:44 2017] GET / => generated 13413 bytes in 228 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 22/29] 127.0.0.1 () {40 vars in 722 bytes} [Fri Jun  9 15:39:44 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 13690|app: 0|req: 3/30] 127.0.0.1 () {40 vars in 737 bytes} [Fri Jun  9 15:39:44 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 13689|app: 0|req: 3/31] 127.0.0.1 () {42 vars in 823 bytes} [Fri Jun  9 15:39:53 2017] GET /cart/ => generated 4799 bytes in 612 msecs (HTTP/1.1 200) 4 headers in 141 bytes (1 switches on core 0)
[pid: 13689|app: 0|req: 4/32] 127.0.0.1 () {42 vars in 828 bytes} [Fri Jun  9 15:39:59 2017] GET /user/info/ => generated 2857 bytes in 160 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 1)
[pid: 13688|app: 0|req: 4/33] 127.0.0.1 () {42 vars in 818 bytes} [Fri Jun  9 15:40:05 2017] GET / => generated 13413 bytes in 111 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 1)
[pid: 13690|app: 0|req: 4/34] 127.0.0.1 () {40 vars in 722 bytes} [Fri Jun  9 15:40:05 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 13688|app: 0|req: 5/35] 127.0.0.1 () {40 vars in 737 bytes} [Fri Jun  9 15:40:05 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 23/36] 127.0.0.1 () {42 vars in 833 bytes} [Fri Jun  9 15:40:08 2017] GET /list1_1_1/ => generated 8260 bytes in 185 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 24/37] 127.0.0.1 () {42 vars in 838 bytes} [Fri Jun  9 15:40:11 2017] GET /list1_2_1/ => generated 8321 bytes in 122 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 1)
[pid: 13691|app: 0|req: 25/38] 127.0.0.1 () {42 vars in 838 bytes} [Fri Jun  9 15:40:14 2017] GET /list1_3_1/ => generated 8234 bytes in 129 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 0)
[pid: 13691|app: 0|req: 26/39] 127.0.0.1 () {42 vars in 838 bytes} [Fri Jun  9 15:40:16 2017] GET /list1_2_1/ => generated 8321 bytes in 130 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 1)
[pid: 13689|app: 0|req: 5/40] 127.0.0.1 () {42 vars in 818 bytes} [Fri Jun  9 17:23:53 2017] GET / => generated 13413 bytes in 1303 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 13689|app: 0|req: 6/41] 127.0.0.1 () {40 vars in 722 bytes} [Fri Jun  9 17:23:55 2017] GET /js/slideshow.js => generated 89 bytes in 449 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
Sat Jun 10 17:41:50 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:49 2017 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:49 2017 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:49 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:50 2017 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:49 2017 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:50 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 10 17:41:50 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jun 10 22:28:51 2017] ***
compiled with version: 5.4.0 20160609 on 28 May 2017 16:03:49
os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017
nodename: ccy-virtual-machine
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ccy/Desktop/pytest/ttsx/dailyfresh/ttshx
writing pidfile to uwsgi.pid
detected binary path: /home/ccy/.virtualenvs/ttsx/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ccy/Desktop/pytest/ttsx/dailyfresh/ttshx
your processes number limit is 7814
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8080 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x23a6f10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 415280 bytes (405 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x23a6f10 pid: 4398 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4398)
spawned uWSGI worker 1 (pid: 4403, cores: 2)
spawned uWSGI worker 2 (pid: 4404, cores: 2)
spawned uWSGI worker 3 (pid: 4405, cores: 2)
spawned uWSGI worker 4 (pid: 4406, cores: 2)
[pid: 4405|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 783 bytes} [Sat Jun 10 22:29:51 2017] GET / => generated 13444 bytes in 554 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 4405|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 706 bytes} [Sat Jun 10 22:29:52 2017] GET /js/slideshow.js => generated 89 bytes in 20 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 4405|app: 0|req: 3/3] 127.0.0.1 () {40 vars in 721 bytes} [Sat Jun 10 22:29:54 2017] GET /js/slideshow.js => generated 89 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 4406|app: 0|req: 1/4] 127.0.0.1 () {40 vars in 738 bytes} [Sat Jun 10 22:29:55 2017] GET /favicon.ico => generated 85 bytes in 567 msecs (HTTP/1.1 404) 3 headers in 125 bytes (1 switches on core 0)
[pid: 4406|app: 0|req: 2/5] 127.0.0.1 () {42 vars in 815 bytes} [Sat Jun 10 22:30:15 2017] GET /user/login/ => generated 3056 bytes in 51 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 1)
读取cookie
{'csrftoken': 'oQSVbm1skBCcNJq79Ge4KAmz8fDva5H8', 'sessionid': 'ozp2tunptgpx9hbg30apnwvlg8exwun4', 'red_url': '/favicon.ico'}
[pid: 4405|app: 0|req: 4/6] 127.0.0.1 () {50 vars in 1011 bytes} [Sat Jun 10 22:30:23 2017] POST /user/login_handle/ => generated 0 bytes in 510 msecs (HTTP/1.1 302) 7 headers in 395 bytes (1 switches on core 1)
[pid: 4405|app: 0|req: 5/7] 127.0.0.1 () {44 vars in 849 bytes} [Sat Jun 10 22:30:24 2017] GET /favicon.ico => generated 85 bytes in 13 msecs (HTTP/1.1 404) 3 headers in 125 bytes (1 switches on core 0)
[pid: 4406|app: 0|req: 3/8] 127.0.0.1 () {40 vars in 776 bytes} [Sat Jun 10 22:30:35 2017] GET / => generated 13413 bytes in 425 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 4406|app: 0|req: 4/9] 127.0.0.1 () {40 vars in 722 bytes} [Sat Jun 10 22:30:35 2017] GET /js/slideshow.js => generated 89 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 4405|app: 0|req: 6/10] 127.0.0.1 () {40 vars in 737 bytes} [Sat Jun 10 22:30:36 2017] GET /js/slideshow.js => generated 89 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 1)
[pid: 4405|app: 0|req: 7/11] 127.0.0.1 () {42 vars in 823 bytes} [Sat Jun 10 22:31:41 2017] GET /cart/ => generated 4799 bytes in 140 msecs (HTTP/1.1 200) 4 headers in 141 bytes (1 switches on core 0)
[pid: 4405|app: 0|req: 8/12] 127.0.0.1 () {42 vars in 808 bytes} [Sat Jun 10 22:31:44 2017] GET / => generated 13413 bytes in 232 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 1)
[pid: 4405|app: 0|req: 9/13] 127.0.0.1 () {40 vars in 722 bytes} [Sat Jun 10 22:31:44 2017] GET /js/slideshow.js => generated 89 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 4406|app: 0|req: 5/14] 127.0.0.1 () {40 vars in 737 bytes} [Sat Jun 10 22:31:45 2017] GET /js/slideshow.js => generated 89 bytes in 7 msecs (HTTP/1.1 404) 3 headers in 129 bytes (1 switches on core 0)
[pid: 4406|app: 0|req: 6/15] 127.0.0.1 () {42 vars in 833 bytes} [Sat Jun 10 22:31:47 2017] GET /list1_1_1/ => generated 8260 bytes in 192 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 1)
[pid: 4405|app: 0|req: 10/16] 127.0.0.1 () {42 vars in 836 bytes} [Sat Jun 10 22:31:49 2017] GET /list1_1_3 => generated 0 bytes in 1 msecs (HTTP/1.1 301) 4 headers in 185 bytes (1 switches on core 1)
[pid: 4403|app: 0|req: 1/17] 127.0.0.1 () {42 vars in 837 bytes} [Sat Jun 10 22:31:49 2017] GET /list1_1_3/ => generated 8245 bytes in 829 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 0)
[pid: 4403|app: 0|req: 2/18] 127.0.0.1 () {42 vars in 838 bytes} [Sat Jun 10 22:31:53 2017] GET /list1_2_3/ => generated 8309 bytes in 88 msecs (HTTP/1.1 200) 4 headers in 146 bytes (1 switches on core 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
